CREATE TABLE user_biometrics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    height numeric NOT NULL,
    user_weight numeric NOT NULL,
    activity numeric NOT NULL,
    gender TEXT NOT NULL,
    age numeric NOT NULL,
    date_created TIMESTAMPTZ DEFAULT Now(),
    user_id INTEGER REFERENCES nutred_users(id) NOT NULL
    );